insert into public.products(name,short_description,category_name,main_image_url,logo_url,visit_url,status,published,featured,tags)
select v.name,v.description,v.category,'/assets/tool-placeholder.svg','/assets/tool-placeholder.svg',v.url,'approved',true,v.featured,v.tags
from jsonb_to_recordset('[
{"name":"Canva","description":"Design and visual content tools.","category":"AI Tools","url":"https://www.canva.com/","featured":true,"tags":["design","ai"]},
{"name":"Microsoft Copilot","description":"AI assistant for work and productivity.","category":"AI Tools","url":"https://copilot.microsoft.com/","featured":true,"tags":["ai","productivity"]},
{"name":"Google Gemini","description":"Google AI assistant for writing and research.","category":"AI Tools","url":"https://gemini.google.com/","featured":true,"tags":["ai","research"]},
{"name":"ChatGPT","description":"AI assistant for writing, learning and coding.","category":"AI Tools","url":"https://chatgpt.com/","featured":true,"tags":["ai","assistant"]},
{"name":"Claude","description":"AI assistant for analysis, writing and coding.","category":"AI Tools","url":"https://claude.ai/","featured":false,"tags":["ai","writing"]},
{"name":"Perplexity AI","description":"AI-powered research and answer engine.","category":"AI Tools","url":"https://www.perplexity.ai/","featured":false,"tags":["ai","research"]},
{"name":"DeepSeek","description":"AI models and assistant for coding and research.","category":"AI Tools","url":"https://www.deepseek.com/","featured":false,"tags":["ai","coding"]},
{"name":"Grok","description":"AI assistant from xAI.","category":"AI Tools","url":"https://grok.com/","featured":false,"tags":["ai"]},
{"name":"Meta AI","description":"AI assistant and creative tools from Meta.","category":"AI Tools","url":"https://www.meta.ai/","featured":false,"tags":["ai"]},
{"name":"CapCut","description":"Video editing and creator tools.","category":"Apps","url":"https://www.capcut.com/","featured":false,"tags":["video","editing"]},
{"name":"Adobe Express","description":"Quick design and content creation.","category":"Apps","url":"https://www.adobe.com/express/","featured":false,"tags":["design"]},
{"name":"Figma","description":"Collaborative interface design and prototyping.","category":"Apps","url":"https://www.figma.com/","featured":false,"tags":["design","ui"]},
{"name":"Grammarly","description":"Writing and communication assistance.","category":"Apps","url":"https://www.grammarly.com/","featured":false,"tags":["writing"]},
{"name":"Notion","description":"Notes, docs and workspace organization.","category":"Apps","url":"https://www.notion.so/","featured":false,"tags":["productivity"]},
{"name":"Trello","description":"Boards and workflow management.","category":"Apps","url":"https://trello.com/","featured":false,"tags":["productivity"]},
{"name":"Slack","description":"Team communication and collaboration.","category":"Apps","url":"https://slack.com/","featured":false,"tags":["communication"]},
{"name":"Zoom","description":"Video meetings and collaboration.","category":"Apps","url":"https://zoom.us/","featured":false,"tags":["meetings"]},
{"name":"Discord","description":"Community and group communication platform.","category":"Apps","url":"https://discord.com/","featured":false,"tags":["community"]},
{"name":"GitHub","description":"Code hosting and developer collaboration.","category":"Websites","url":"https://github.com/","featured":false,"tags":["developer"]},
{"name":"GitHub Copilot","description":"AI coding assistance.","category":"Websites","url":"https://github.com/features/copilot","featured":false,"tags":["developer","ai"]},
{"name":"Cursor","description":"AI-powered code editor.","category":"Websites","url":"https://www.cursor.com/","featured":false,"tags":["developer","ai"]},
{"name":"Replit","description":"Browser-based coding and app development.","category":"Websites","url":"https://replit.com/","featured":false,"tags":["developer"]},
{"name":"Google Drive","description":"Cloud storage and collaboration.","category":"Websites","url":"https://drive.google.com/","featured":false,"tags":["storage"]},
{"name":"Dropbox","description":"Cloud file storage and sharing.","category":"Websites","url":"https://www.dropbox.com/","featured":false,"tags":["storage"]},
{"name":"Google Docs","description":"Online document creation and collaboration.","category":"Websites","url":"https://docs.google.com/","featured":false,"tags":["productivity"]},
{"name":"Microsoft 365","description":"Productivity apps and cloud services.","category":"Websites","url":"https://www.microsoft.com/microsoft-365","featured":false,"tags":["productivity"]},
{"name":"LinkedIn","description":"Professional networking platform.","category":"Websites","url":"https://www.linkedin.com/","featured":false,"tags":["career"]},
{"name":"Facebook","description":"Social networking platform.","category":"Websites","url":"https://www.facebook.com/","featured":false,"tags":["social"]},
{"name":"Instagram","description":"Photo, video and creator platform.","category":"Websites","url":"https://www.instagram.com/","featured":false,"tags":["social"]},
{"name":"TikTok","description":"Short-form video creator platform.","category":"Websites","url":"https://www.tiktok.com/","featured":false,"tags":["social","video"]},
{"name":"WhatsApp","description":"Messaging and calling platform.","category":"Apps","url":"https://www.whatsapp.com/","featured":false,"tags":["messaging"]},
{"name":"YouTube","description":"Video publishing and learning platform.","category":"Websites","url":"https://www.youtube.com/","featured":false,"tags":["video"]},
{"name":"X","description":"Social network for public conversation.","category":"Websites","url":"https://x.com/","featured":false,"tags":["social"]},
{"name":"Reddit","description":"Community discussion and discovery platform.","category":"Websites","url":"https://www.reddit.com/","featured":false,"tags":["community"]},
{"name":"Amazon","description":"Online shopping marketplace.","category":"Websites","url":"https://www.amazon.com/","featured":false,"tags":["shopping"]},
{"name":"eBay","description":"Online marketplace.","category":"Websites","url":"https://www.ebay.com/","featured":false,"tags":["shopping"]},
{"name":"AliExpress","description":"Global online marketplace.","category":"Websites","url":"https://www.aliexpress.com/","featured":false,"tags":["shopping"]},
{"name":"Walmart","description":"Retail marketplace and shopping platform.","category":"Websites","url":"https://www.walmart.com/","featured":false,"tags":["shopping"]},
{"name":"Booking.com","description":"Travel accommodation and booking platform.","category":"Websites","url":"https://www.booking.com/","featured":false,"tags":["travel"]},
{"name":"Airbnb","description":"Accommodation and travel marketplace.","category":"Websites","url":"https://www.airbnb.com/","featured":false,"tags":["travel"]},
{"name":"Netflix","description":"Streaming entertainment service.","category":"Websites","url":"https://www.netflix.com/","featured":false,"tags":["entertainment"]},
{"name":"Spotify","description":"Music and audio streaming service.","category":"Apps","url":"https://www.spotify.com/","featured":false,"tags":["music"]},
{"name":"Pinterest","description":"Visual discovery and inspiration platform.","category":"Websites","url":"https://www.pinterest.com/","featured":false,"tags":["inspiration"]},
{"name":"Telegram","description":"Messaging and community platform.","category":"Apps","url":"https://telegram.org/","featured":false,"tags":["messaging"]},
{"name":"Google","description":"Search and online services.","category":"Websites","url":"https://www.google.com/","featured":false,"tags":["search"]},
{"name":"Bing","description":"Search and web discovery platform.","category":"Websites","url":"https://www.bing.com/","featured":false,"tags":["search"]},
{"name":"Wikipedia","description":"Free community-built encyclopedia.","category":"Websites","url":"https://www.wikipedia.org/","featured":false,"tags":["reference"]}
]'::jsonb) v(name text,description text,category text,url text,featured boolean,tags text[])
where not exists(select 1 from public.products p where p.name=v.name);